//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuno.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kuno.CodeAnalysis.RuleStrings", typeof(RuleStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string K1000_Category {
            get {
                return ResourceManager.GetString("K1000_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields in messages indicate that there might be some logic when there shouldn’t be. Fields also are not serialized by default. Remove any fields from message classes or replace them with properties..
        /// </summary>
        internal static string K1000_Description {
            get {
                return ResourceManager.GetString("K1000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string K1000_IsActivatedByDefault {
            get {
                return ResourceManager.GetString("K1000_IsActivatedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string K1000_Severity {
            get {
                return ResourceManager.GetString("K1000_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages should not contain fields..
        /// </summary>
        internal static string K1000_Title {
            get {
                return ResourceManager.GetString("K1000_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.kuno.io/rules/1000.
        /// </summary>
        internal static string K1000_Url {
            get {
                return ResourceManager.GetString("K1000_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string K1001_Category {
            get {
                return ResourceManager.GetString("K1001_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages must be immutable. Remove the setter from all properties or set the setter to private..
        /// </summary>
        internal static string K1001_Description {
            get {
                return ResourceManager.GetString("K1001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string K1001_IsActivatedByDefault {
            get {
                return ResourceManager.GetString("K1001_IsActivatedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string K1001_Severity {
            get {
                return ResourceManager.GetString("K1001_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message properties must be read-only..
        /// </summary>
        internal static string K1001_Title {
            get {
                return ResourceManager.GetString("K1001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.kuno.io/rules/1001.
        /// </summary>
        internal static string K1001_Url {
            get {
                return ResourceManager.GetString("K1001_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string K1002_Category {
            get {
                return ResourceManager.GetString("K1002_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string K1002_Description {
            get {
                return ResourceManager.GetString("K1002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string K1002_IsActivatedByDefault {
            get {
                return ResourceManager.GetString("K1002_IsActivatedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string K1002_Severity {
            get {
                return ResourceManager.GetString("K1002_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message properties must be public..
        /// </summary>
        internal static string K1002_Title {
            get {
                return ResourceManager.GetString("K1002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string K1003_Category {
            get {
                return ResourceManager.GetString("K1003_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string K1003_Description {
            get {
                return ResourceManager.GetString("K1003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string K1003_Severity {
            get {
                return ResourceManager.GetString("K1003_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message properties must be set in the constructor..
        /// </summary>
        internal static string K1003_Title {
            get {
                return ResourceManager.GetString("K1003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string K1100_Category {
            get {
                return ResourceManager.GetString("K1100_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string K1100_Description {
            get {
                return ResourceManager.GetString("K1100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string K1100_IsActivatedByDefault {
            get {
                return ResourceManager.GetString("K1100_IsActivatedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string K1100_Severity {
            get {
                return ResourceManager.GetString("K1100_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests should end in &apos;Request&apos;..
        /// </summary>
        internal static string K1100_Title {
            get {
                return ResourceManager.GetString("K1100_Title", resourceCulture);
            }
        }
    }
}
